# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RPFeedbackExample' do
  use_frameworks!

  pod 'RPiOSFeedback', :path => '~/Desktop/Projects/ReviewPush/RPAppStoreFeedback'

end
